### ISSUE TITLE
[help] anular supscripcion automatica cuando un elemento es remplazado en el dom

### ISSUE THREAD

**Issue by redfox-mx** [BBVA/open-cells#11]
Tengo entendido que por motivos de diseño anteriormente los canales estaban diseñados para no eliminar sus suscripciones automaticamente y la unica forma era hacerla manualmente, sin embargo, siempre me quedo la duda, es esto asi? ¿En que momento se anulan las supbcripciones? ¿Se retienen aun cuando los elemento ya no son mas parte del dom?

Esta duda viene porque muchos de los frameworks (como angular) u otras bibliotecas siempre hacen hincapié en la liberación de recursos cuando ya no se necesita mas una susbcripcion, si bien el subject (aka. channel) debe seguir vivo, no veo razón para no eliminar una subscripcion una vez el `viewLimit` a llegado al maximo y se empezara a disponer de nodos del DOM

atte: diegojesus.hernandez.gonzalez@bbva.com

**Comment by jariaspe** [comment]
Hola @redfox-mx 

La gestión de recursos que hace rxjs de los canales nunca ha supuesto ningún problema e internamente lo usamos en aplicaciones muy muy grandes con muchas páginas y canales.

Un saludo.
