### ISSUE TITLE
[templates]: update minimal scafollding for typescript configurations

### ISSUE THREAD

**Issue by redfox-mx** [BBVA/open-cells#13]
Actualmente los templates (exmaples) contienen una configuración que no coincide con los requerimientos de los proyectos. Por ejemplo:

https://github.com/BBVA/open-cells/blob/f5c682786daae950ca95c36383c87e715480b23b/packages/example/recipes-app/tsconfig.json#L7-L9

no se deben emitir declaration files para aplicaciones ya que solo nos proporcionan typechecking en vite.

no es necesario usar las opciones de sourceMap ya que estas no son manejadas por tsc, son generadas por vite (internamente rollup y esbuild)

no es necesario importHelpers ya que esbuild no lee esa configuración

https://github.com/BBVA/open-cells/blob/f5c682786daae950ca95c36383c87e715480b23b/packages/example/recipes-app/tsconfig.json#L21

para el typecheck de aplicaciones, no es necesario emitir ningún tipo de archivo de declaraciones ya que no seran usadas

https://github.com/BBVA/open-cells/blob/f5c682786daae950ca95c36383c87e715480b23b/packages/example/recipes-app/tsconfig.json#L23

Ya que solo ocuparemos el tsc para hacer un typecheck no es necesario configurar un outDir

atte: diegojesus.hernandez.gonzalez@bbva.com

**Comment by jariaspe** [comment]
Hola @redfox-mx

Cuando dices que "no coincide con los requerimientos de los proyectos", ¿a qué proyectos te refieres?

Un saludo.

**Comment by redfox-mx** [comment]
Hola @jariaspe un gusto conocerte.

En concreto, ninguno, es más un error de redacción mío. Sin embargo si creo que se podrían descartar las mismas opciones para mantener mínimas para el desarrollo con estos templates. Sobre todo porque no se usan ya que el typecheck no depende de que se emitan las declaraciones de tipos. 

Pd: ahora que leo mis comentarios creo que si suenan bastante secos, mil disculpas. Me emocionó que el cells fuera de proyecto abierto y los comentarios fueron ya en la noche cansado. Ojalá puedan servir mir comentario en algo n.n 

Saludos

**Comment by jariaspe** [comment]
Hola @redfox-mx 

Ten en cuenta que esa es la configuración de un "simple" scaffold que nos ha servido a nosotros para publicar la aplicación de ejemplo y/o el scaffold vacío. A partir de ahí cada proyecto puede adaptarla como mejor convenga a sus necesidades.

En próximas release revisaremos si es necesario eliminar alguna configuración.

PD. Como te decía en otra issue todo el feedback es bienvenido ya puede hacernos ver puntos de vista que se nos pueden haber pasado a nosotros. Pero siempre con respeto a todas las personas de la comunidad y a su trabajo.

Un saludo.
