### ISSUE TITLE
[core]: update code quality and optimizations

### ISSUE THREAD

**Issue by redfox-mx** [BBVA/open-cells#15]
Hola equipo, revisando un poco el repo, me di cuenta que algunar partes tienen ciertos fragmentos de codigo que pueden ser optimizados y refactorisados para mejorar la legibilidad y el performance. Un ejemplo es este

https://github.com/BBVA/open-cells/blob/f5c682786daae950ca95c36383c87e715480b23b/packages/core/src/manager/bridge-channels.js#L366-L382

En este ejemplo, se puede quitar el optional chaining ya que el metodo filter ya regreso un arreglo sin valores undefined

https://github.com/BBVA/open-cells/blob/f5c682786daae950ca95c36383c87e715480b23b/packages/core/src/manager/bridge-channels.js#L381

De la misma manera el reducer puede ser sustituido por el metodo flat() para lograr el mismo efecto.  La ventaja es que los metodos propios del ecmascript ya estan mejor optimizados y en este caso, previene la iteración continua que se tiene que hacer en cada concat

```ts
  .filter(c => c !== undefined)
  .flat();
```

De la misma manera que no es necesario usar el ultimo operador or ya que map, filter y flat siempre devuelven un array.

La verdad es que el bridge es una propuesta interesante, pero creo que le ha faltado amor y mantenimiento en los ultimos años

atte: diegojesus.hernandez.gonzalez@bbva.com

**Comment by jariaspe** [comment]
Hola @redfox-mx 

Tal como indicamos en nuestro código de conducta los comentarios tienen que tener empatía y ser constructivos. Y francamente la frase _creo que le ha faltado amor y mantenimiento en los ultimos años_ muestra cero empatía.

Estaremos encantados de recibir tu feedback y propuestas siempre que respetes el trabajo de todas las personas que participan en la comunidad.

Un saludo.
