### ISSUE TITLE
Uso de inbound y outbounds

### ISSUE THREAD

**Issue by MisterMAM** [BBVA/open-cells#7]
Buenas,

Estoy intentando utilizar las bounded properties para simplificar este código:
`
this.controller.subscribe("ch_tasks", (tasks: Task[]) => {
      this.tasks = tasks;
    });
`
Para definir las inbounds he añadido lo siguiente:
`
static inbounds = {
    tasks: { channel: 'ch_tasks' }
  }
`
Y la intento usar de la siguiente manera:
`
${this.tasks.map((task: Task) => {
 // ...
)}
`
Pero lógicamente me indica que la propiedad tasks no existe. He intentado acceder de manera estática, a través del controlador y nada. He hecho la prueba de añadir un action para ver si está recibiendo el valor y si lo recibe pero no está seteando la propiedad:
`
tasks: { channel: 'ch_tasks', action: (data: Task[]) => {
      console.log(data);
      return data;
    } }
`

Tampoco he encontrado su uso en la aplicación de ejemplo para poder ver cómo lo implementáis y en la documentación tampoco hay nada referente al uso de las bounded properties, únicamente de su declaración.

Gracias por la ayuda!

**Comment by MisterMAM** [comment]
Solucionado, error absurdo debido a que no había ninguna data en el channel y fallaba porque el valor era null no porque no existiera la propiedad, por si a alguien más le pasa.

**Comment by davidigza** [comment]
Buenos días tienes la documentación aquí https://www.opencells.dev/docs/state/bounded-props/index.html espero que te sirva de ayuda.
