### ISSUE TITLE
[help] This repo can be used as reference for other projects?

### ISSUE THREAD

**Issue by redfox-bbva** [BBVA/open-cells#8]
Muy buenas noches equipo, saludos.

Actualmente me encuentro desarrollando (de manera proactiva, no oficial) una devtool para cells, si bien aun no esta terminada, me gustaría saber si este proyecto va a ser mantenido de manera activa y si esta abierto a poder contribuir?

Asi mismo, saber si es factible usar los tipos que incluyen para versiones de bridge productivas (<= 19.x)

**Comment by jariaspe** [comment]
Hola @redfox-bbva,

Salvo que nos cambien las prioridades del proyecto, este repo va a ser mantenido de manera activa. Sobre las contribuciones, por su puesto las aceptamos aunque como indicamos en [CONTRIBUTING.md](https://github.com/BBVA/open-cells/blob/main/CONTRIBUTING.md) en una primera fase hasta que estabilicemos la metodología preferimos la apertura de issues que nosotros nos encargaremos de llevar al código a las PRs. 

Lo único sí que te diría que tienes que diferenciar entre este repo y el bridge interno al que te refieres, ya que a día de hoy son cosas separadas.

Un saludo.
